### ISSUE TITLE
Фиксированный размер контейнера.

### ISSUE THREAD

**Issue by EKoretsky** [Vera-Junior/wayup-test#2]
Вера, у тебя задан фиксированный размер контейнера, и уже на 1280 появляется горизонтальный скролл( полоса прокрутки)

**Comment by Vera-Junior** [comment]
Спасибо большое ))) надо будет убрать
следующее задание будет на адаптивность ) избавлюсь от этого

**Comment by Vera-Junior** [comment]
хммм как то странно размер контейнера 1170 по идеи на 1280 не должно быть прокрутки. 
 а масштаб экрана у Вас стоит 100?
хотя если запилить адаптивность этот вопрос отпадет )

**Comment by EKoretsky** [comment]
Дико извиняюсь.  Видно тоже под вечер устал и не заметил как масштаб поменян в браузере=)   Закрываю проблему.=)

**Comment by Vera-Junior** [comment]
Ох я так туплю в последние дни из за недосыпа ) поэтому не страшно. 
зато проверка себя на всякий случай не помешает) 

Спасибо, что посмотрели  очень благодарна=)
